name: 'GitHub Action Template'
description: Just a template for your new GitHub Action
author: Ian Welerson
branding:
  icon: git-merge
  color: red
inputs:
  github-token:
    description: github token
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'